# Generated by Django 5.0.1 on 2026-02-04 22:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Company code (e.g., YGY)", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(help_text="Company name", max_length=200)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Jakarta", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "point_expiry_months",
                    models.IntegerField(
                        default=12,
                        help_text="Points expire after X months (0 = never expire)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "points_per_currency",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Points earned per currency unit (e.g., 1.00 = 1 point per Rp 1)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "company",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="company_code_2351f9_idx"),
                    models.Index(
                        fields=["is_active"], name="company_is_acti_997df1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Brand code (e.g., YGY-001)", max_length=20
                    ),
                ),
                ("name", models.CharField(help_text="Brand name", max_length=200)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "tax_id",
                    models.CharField(blank=True, help_text="NPWP", max_length=50),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=11.0,
                        help_text="Tax rate in percentage (e.g., 11.00 for 11%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Service charge in percentage (e.g., 5.00 for 5%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "point_expiry_months_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override company point expiry policy (leave blank to use company default)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "db_table": "brand",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "store_code",
                    models.CharField(
                        help_text="Store code (e.g., YGY-001-BSD)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "store_name",
                    models.CharField(help_text="Store name", max_length=200),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("timezone", models.CharField(default="Asia/Jakarta", max_length=50)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Parent company that owns this store",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
                "db_table": "store",
                "ordering": ["store_name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("cashier", "Cashier"),
                            ("waiter", "Waiter"),
                            ("kitchen", "Kitchen Staff"),
                        ],
                        default="cashier",
                        max_length=20,
                    ),
                ),
                (
                    "role_scope",
                    models.CharField(
                        choices=[
                            ("global", "Global Level"),
                            ("company", "Company Level"),
                            ("brand", "Brand Level"),
                            ("store", "Store Level"),
                        ],
                        default="store",
                        help_text="Authorization scope for this user",
                        max_length=20,
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        help_text="6-digit PIN for POS login and approvals",
                        max_length=6,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="user_photos/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for company-wide users",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.brand",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company affiliation (can be null if company is deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.company",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for brand/company-wide users",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="StoreBrand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is this brand currently active in this store?",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="When this brand started operating in this store",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When this brand stopped operating (if applicable)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_stores",
                        to="core.brand",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_brands",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Brand",
                "verbose_name_plural": "Store Brands",
                "db_table": "store_brand",
            },
        ),
        migrations.AddField(
            model_name="store",
            name="brands",
            field=models.ManyToManyField(
                help_text="Brands/tenants operating in this store",
                related_name="stores",
                through="core.StoreBrand",
                to="core.brand",
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["company", "is_active"], name="brand_company_911aa5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["code"], name="brand_code_5807fc_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="brand",
            unique_together={("company", "code")},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["company", "is_active"], name="user_company_2ce59c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["brand", "is_active"], name="user_brand_i_95cde7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="user_role_3744fd_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role_scope"], name="user_role_sc_966ff8_idx"),
        ),
        migrations.AddIndex(
            model_name="storebrand",
            index=models.Index(
                fields=["store", "is_active"], name="store_brand_store_i_e5ac4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storebrand",
            index=models.Index(
                fields=["brand", "is_active"], name="store_brand_brand_i_5c220e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storebrand",
            index=models.Index(
                fields=["store", "brand", "is_active"],
                name="store_brand_store_i_6230eb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storebrand",
            unique_together={("store", "brand")},
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["company", "is_active"], name="store_company_4d2bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["store_code"], name="store_store_c_467bec_idx"),
        ),
    ]
