# Generated by Django 5.0.1 on 2026-02-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productphoto",
            name="checksum",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MD5 checksum for integrity",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="content_type",
            field=models.CharField(default="image/jpeg", max_length=100),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="filename",
            field=models.CharField(
                blank=True, default="", help_text="Original filename", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="object_key",
            field=models.CharField(
                blank=True, default="", help_text="MinIO object key", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="size",
            field=models.IntegerField(default=0, help_text="File size in bytes"),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productphoto",
            name="version",
            field=models.IntegerField(default=1, help_text="Image version for sync"),
        ),
        migrations.AlterField(
            model_name="productphoto",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="product_photos/"),
        ),
        migrations.AddIndex(
            model_name="productphoto",
            index=models.Index(
                fields=["object_key"], name="product_pho_object__284542_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productphoto",
            index=models.Index(
                fields=["checksum"], name="product_pho_checksu_8ad77c_idx"
            ),
        ),
    ]
