# Generated by Django 5.0.1 on 2026-02-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tables",
            name="shape",
            field=models.CharField(
                choices=[
                    ("round", "Round"),
                    ("square", "Square"),
                    ("rectangle", "Rectangle"),
                ],
                default="square",
                help_text="Table shape (round, square, rectangle)",
                max_length=20,
            ),
        ),
    ]
